#Data cleaning

In [4]:
import pandas as pd

df = pd.read_csv("../data/raw/amazon_dataset.csv")

C:\Users\prath\AppData\Local\Temp\ipykernel_18268\1111577921.py:3: DtypeWarning: Columns (0: Unnamed: 22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/amazon_dataset.csv")

## Missing Value Analysis

This step identifies missing values in each column.

Understanding missing values helps determine whether data cleaning is required before analysis.

In [5]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

### Observation

- Most columns have no missing values.
- The `fulfilled-by` column has approximately 70% missing values.
- `promotion-ids` has around 38% missing values.
- The `Amount` column has around 6% missing values, which is important because it affects revenue calculations.

### Business Interpretation

Not every missing value indicates poor-quality data. Some may represent legitimate business situations, such as orders placed without promotional codes. These columns will be investigated further before deciding whether to remove or transform them.

# Total sum of null values in each column

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.isnull().sum() / len(df) * 100

index                  0.000000
Order ID               0.000000
Date                   0.000000
Status                 0.000000
Fulfilment             0.000000
Sales Channel          0.000000
ship-service-level     0.000000
Style                  0.000000
SKU                    0.000000
Category               0.000000
Size                   0.000000
ASIN                   0.000000
Courier Status         5.328164
Qty                    0.000000
currency               6.043807
Amount                 6.043807
ship-city              0.025586
ship-state             0.025586
ship-postal-code       0.025586
ship-country           0.025586
promotion-ids         38.110487
B2B                    0.000000
fulfilled-by          69.546811
Unnamed: 22           38.030626
dtype: float64

In [8]:
df.nunique()

index                 128975
Order ID              120378
Date                      91
Status                    13
Fulfilment                 2
Sales Channel              2
ship-service-level         2
Style                   1377
SKU                     7195
Category                   9
Size                      11
ASIN                    7190
Courier Status             3
Qty                       10
currency                   1
Amount                  1410
ship-city               8955
ship-state                69
ship-postal-code        9459
ship-country               1
promotion-ids           5787
B2B                        2
fulfilled-by               1
Unnamed: 22                1
dtype: int64

# Data Cleaning

## Missing Value Investigation

In [9]:
df[df["Amount"].isnull()]

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
8,8,407-5443024-5233168,4/30/2022,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,...,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
29,29,404-5933402-8801952,4/30/2022,Cancelled,Merchant,Amazon.in,Standard,JNE2132,JNE2132-KR-398-XXXL,kurta,...,NaN,NaN,GUWAHATI,ASSAM,781003.0,IN,NaN,False,Easy Ship,NaN
65,65,171-4137548-0481151,4/30/2022,Cancelled,Amazon,Amazon.in,Expedited,JNE3373,JNE3373-KR-XXL,kurta,...,NaN,NaN,Dahod,Gujarat,389151.0,IN,NaN,False,NaN,NaN
84,84,403-9950518-0349133,4/30/2022,Cancelled,Amazon,Amazon.in,Expedited,JNE3510,JNE3510-KR-M,kurta,...,NaN,NaN,HYDERABAD,TELANGANA,500072.0,IN,NaN,False,NaN,NaN
95,95,405-9112089-3379536,4/30/2022,Cancelled,Amazon,Amazon.in,Expedited,JNE3405,JNE3405-KR-L,kurta,...,NaN,NaN,PUNE,MAHARASHTRA,411046.0,IN,NaN,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128903,128903,406-3923120-4345139,5/31/2022,Cancelled,Amazon,Amazon.in,Expedited,JNE3801,JNE3801-KR-M,kurta,...,NaN,NaN,ANANTAPUR,ANDHRA PRADESH,515001.0,IN,NaN,False,NaN,False
128907,128907,403-6757403-6097100,5/31/2022,Cancelled,Amazon,Amazon.in,Expedited,NW014,NW014-ST-SR-XXXL,Set,...,NaN,NaN,GREATER NOIDA,UTTAR PRADESH,201306.0,IN,NaN,False,NaN,False
128908,128908,403-6757403-6097100,5/31/2022,Cancelled,Amazon,Amazon.in,Expedited,NW007,NW007-ST-CP-XXXL,Set,...,NaN,NaN,GREATER NOIDA,UTTAR PRADESH,201306.0,IN,NaN,False,NaN,False
128958,128958,408-9513596-4393945,5/31/2022,Cancelled,Amazon,Amazon.in,Expedited,SET058,SET058-KR-NP-L,Set,...,NaN,NaN,Bengaluru,KARNATAKA,560037.0,IN,NaN,False,NaN,False
128967,128967,404-5182288-1653947,5/31/2022,Cancelled,Amazon,Amazon.in,Expedited,JNE3638,JNE3638-KR-XS,kurta,...,NaN,NaN,Kolkata,WEST BENGAL,700040.0,IN,NaN,False,NaN,False

Observation:

- Rows with missing Amount appear to...
- Currency is also...
- Most of these orders are...

In [10]:
df[df["fulfilled-by"].isnull()]

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
2,2,404-0687676-7273146,4/30/2022,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.0,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
4,4,407-1069790-7240320,4/30/2022,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.0,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN
5,5,404-1490984-4578765,4/30/2022,Shipped,Amazon,Amazon.in,Expedited,SET264,SET264-KR-NP-XL,Set,...,INR,824.0,GHAZIABAD,UTTAR PRADESH,201102.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
6,6,408-5748499-6859555,4/30/2022,Shipped,Amazon,Amazon.in,Expedited,J0095,J0095-SET-L,Set,...,INR,653.0,CHANDIGARH,CHANDIGARH,160036.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
8,8,407-5443024-5233168,4/30/2022,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,...,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,128970,406-6001380-7673107,5/31/2022,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,...,INR,517.0,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN,False
128971,128971,402-9551604-7544318,5/31/2022,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,...,INR,999.0,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128972,128972,407-9547469-3152358,5/31/2022,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,...,INR,690.0,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN,False
128973,128973,402-6184140-0545956,5/31/2022,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,INR,1199.0,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128974,128974,408-7436540-8728312,5/31/2022,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,...,INR,696.0,Raipur,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False

Observation:
Most values are missing.
Only some orders are fulfilled using "Easy Ship".
Missing values may indicate orders fulfilled by another method.

In [11]:
df[df["promotion-ids"].isnull()]

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,4/30/2022,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
3,3,403-9615377-8133951,4/30/2022,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,4/30/2022,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN
9,9,402-4393761-0311520,4/30/2022,Shipped,Amazon,Amazon.in,Expedited,JNE3461,JNE3461-KR-XXL,kurta,...,INR,363.00,Chennai,TAMIL NADU,600041.0,IN,NaN,False,NaN,NaN
10,10,407-5633625-6970741,4/30/2022,Shipped,Amazon,Amazon.in,Expedited,JNE3160,JNE3160-KR-G-S,kurta,...,INR,685.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128966,128966,406-9812666-2474761,5/31/2022,Shipped,Amazon,Amazon.in,Expedited,SET224,SET224-KR-NP-XS,Set,...,INR,1132.00,CHENNAI 600042,TAMIL NADU,600042.0,IN,NaN,False,NaN,False
128967,128967,404-5182288-1653947,5/31/2022,Cancelled,Amazon,Amazon.in,Expedited,JNE3638,JNE3638-KR-XS,kurta,...,NaN,NaN,Kolkata,WEST BENGAL,700040.0,IN,NaN,False,NaN,False
128969,128969,404-3802633-7250760,5/31/2022,Cancelled,Amazon,Amazon.in,Expedited,SET044,SET044-KR-NP-M,Set,...,INR,612.00,MUMBAI,MAHARASHTRA,400017.0,IN,NaN,False,NaN,False
128970,128970,406-6001380-7673107,5/31/2022,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,...,INR,517.00,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN,False
128972,128972,407-9547469-3152358,5/31/2022,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,...,INR,690.00,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN,False

Observation:
Promotion IDs are missing for many orders.
This likely indicates that no promotion was applied.

# Data Cleaning Decisions

In [12]:
df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by', 'Unnamed: 22'],
      dtype='str')

In [13]:
df = df.drop(columns=["Unnamed: 22"])

In [14]:
df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by'],
      dtype='str')

In [15]:
df.duplicated().sum()

np.int64(0)

Observation:
No duplicate rows found.
No action required.

| Column        | Missing?         | Action                  |
| ------------- | ---------------- | ----------------------- |
| Amount        | Yes              | Investigate further     |
| Currency      | Yes              | Investigate further     |
| fulfilled-by  | Yes              | Keep (business meaning) |
| promotion-ids | Yes              | Keep (business meaning) |
| Unnamed: 22   | Yes (almost all) | Remove                  |

In [16]:
df.shape

(128975, 23)

In [17]:
df[df["Amount"].isnull()][["Amount", "currency"]].head(100)

      Amount currency
8        NaN      NaN
29       NaN      NaN
65       NaN      NaN
84       NaN      NaN
95       NaN      NaN
...      ...      ...
1263     NaN      NaN
1274     NaN      NaN
1282     NaN      NaN
1283     NaN      NaN
1287     NaN      NaN

[100 rows x 2 columns]

In [18]:
df = df.dropna(subset=["Amount"])

In [19]:
df.shape

(121180, 23)

In [20]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         5136
Qty                       0
currency                  0
Amount                    0
ship-city                31
ship-state               31
ship-postal-code         31
ship-country             31
promotion-ids         41698
B2B                       0
fulfilled-by          83639
dtype: int64

## Cleaning Performed

- Removed the unnecessary 'Unnamed: 22' column.
- Removed rows where Amount was missing.
- Kept 'fulfilled-by' because missing values indicate non-Easy Ship orders.
- Kept 'promotion-ids' because missing values likely mean no promotion was applied.
- No duplicate rows were found.

In [21]:
df.to_csv("../data/processed/amazon_cleaned.csv", index=False)

In [22]:
import os
os.listdir("../data/processed")

['amazon_cleaned.csv']

In [23]:
df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by'],
      dtype='str')

In [24]:
df.shape

(121180, 23)

In [25]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         5136
Qty                       0
currency                  0
Amount                    0
ship-city                31
ship-state               31
ship-postal-code         31
ship-country             31
promotion-ids         41698
B2B                       0
fulfilled-by          83639
dtype: int64

## Handling Missing Values

Missing values were investigated before cleaning. Columns such as `promotion-ids`,
`fulfilled-by`, and `Courier Status` contain missing values that can represent
non-applicable or unavailable information rather than data-entry errors.

For shipping location fields, rows with missing values will be removed because
these fields are important for regional analysis.

In [26]:
# Remove rows with missing shipping location information
df = df.dropna(
    subset=["ship-city", "ship-state", "ship-postal-code", "ship-country"]
)

# Fill non-applicable categorical fields
df["Courier Status"] = df["Courier Status"].fillna("Not Available")
df["promotion-ids"] = df["promotion-ids"].fillna("No Promotion")
df["fulfilled-by"] = df["fulfilled-by"].fillna("Not Specified")

# Check remaining missing values
df.isnull().sum()

index                 0
Order ID              0
Date                  0
Status                0
Fulfilment            0
Sales Channel         0
ship-service-level    0
Style                 0
SKU                   0
Category              0
Size                  0
ASIN                  0
Courier Status        0
Qty                   0
currency              0
Amount                0
ship-city             0
ship-state            0
ship-postal-code      0
ship-country          0
promotion-ids         0
B2B                   0
fulfilled-by          0
dtype: int64

In [27]:
df.shape

(121149, 23)

## Data Type Validation

We now check whether each column has an appropriate data type for analysis.

In [28]:
df.dtypes

index                   int64
Order ID                  str
Date                      str
Status                    str
Fulfilment                str
Sales Channel             str
ship-service-level        str
Style                     str
SKU                       str
Category                  str
Size                      str
ASIN                      str
Courier Status            str
Qty                     int64
currency                  str
Amount                float64
ship-city                 str
ship-state                str
ship-postal-code      float64
ship-country              str
promotion-ids             str
B2B                      bool
fulfilled-by              str
dtype: object

In [29]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

In [30]:
df[["Qty", "Amount"]].dtypes

Qty         int64
Amount    float64
dtype: object

In [31]:
df[["Qty", "Amount"]] = df[["Qty", "Amount"]].apply(
    pd.to_numeric, errors="coerce"
)

In [32]:
df[["Qty", "Amount"]].dtypes

Qty         int64
Amount    float64
dtype: object

In [34]:
df = df.drop(columns=["index"])

In [35]:
df.shape

(121149, 22)

In [36]:
df.isnull().sum()

Order ID              0
Date                  0
Status                0
Fulfilment            0
Sales Channel         0
ship-service-level    0
Style                 0
SKU                   0
Category              0
Size                  0
ASIN                  0
Courier Status        0
Qty                   0
currency              0
Amount                0
ship-city             0
ship-state            0
ship-postal-code      0
ship-country          0
promotion-ids         0
B2B                   0
fulfilled-by          0
dtype: int64

In [37]:
df.head()

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by
0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,...,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,No Promotion,False,Easy Ship
1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,...,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,...,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,Not Specified
3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,...,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,No Promotion,False,Easy Ship
4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,...,1,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,No Promotion,False,Not Specified

In [38]:
df.to_csv("../data/processed/amazon_cleaned.csv", index=False)

In [39]:
import os

os.path.getsize("../data/processed/amazon_cleaned.csv") / (1024 * 1024)

65.16207504272461